# Options:
# clean: Remove dead symbolic links that point to the dotfiles directory. Unless
#        the force option is set to true.
# relink: remove existing target but only if it's a symbolic link
# force: remove existing target even if it's a file or directory

- defaults:
    link:
        force: true

- clean: ['~']

- link:
    ~/.zshrc: zshrc
    ~/.bashrc: bashrc
    ~/.hyper.js: hyper.js
    ~/.vim: vim/.vim/
    ~/.vimrc: vim/vimrc
    ~/.config/nvim:
        create: true
        path: vim/.vim/
    ~/.config/nvim/init.vim:
        create: true
        path: vim/.vimrc
    ~/.tmux.conf: tmux.conf
    ~/.gitconfig: gitconfig
    ~/.ctags: ctags
    ~/.colordiffrc: colordiffrc
    ~/.tldrrc: tldrrc
    ~/.pandoc: pandorc
    ~/.dotfiles: ''

- shell:
    - [git submodule update --init --recursive, Installing/Updating submodules]
    - [curl -L git.io/antigen > antigen.zsh, Installing Antigen]

