- clean: ['~']

- link:
        ~/.zshrc:
                force: true
                path: zshrc
        ~/.vim:
                force: true
                path: vim/.vim/
        ~/.vimrc:
                force: true
                path: vim/.vimrc
        ~/.tmux.conf:
                force: true
                path: tmux.conf
        ~/.gitconfig:
                force: true
                path: gitconfig
        ~/.dotfiles: ''


- shell:
        - [git submodule update --init --recursive, Installing/Updating submodules]

