- link:
        ~/.config/sublime-text-3/Packages/User:
                create: true
                path: sublime-text-3/User
        ~/.config/sublime-text-3/Installed Packages:
                create: true
                path: sublime-text-3/Installed Packages
        ~/.config/terminator/config:
                create: true
                path: terminator/config
        ~/.fonts: fonts
        ~/.themes: themes
