- clean: ['~']

- link:
    ~/Library/Application Support/Sublime Text 3/Packages/User:
        create: true
        path: sublime-text-3/User/
        force: true
    ~/Library/Application Support/Sublime Text 3/Installed Packages:
        create: true
        path: sublime-text-3/Installed Packages/
        force: true

# TODO: Checkout https://gist.github.com/garethrees/2470157
# TODO: Remind me why you're not using a simple bash script?
# TODO: Turn off dashboard: defaults write com.apple.dashboard mcx-disabled -boolean TRUE; killall Dock

- shell:
    # - [defaults write com.apple.Dock autohide-delay -float 0 && killall Dock, Remove the delay for Auto-Hide & Auto-Show of Dock]
    # - [defaults write com.apple.dock autohide-time-modifier -int 0;killall Dock, Remove dock animation]
    # - [defaults write NSGlobalDomain NSTableViewDefaultSizeMode -int 1, Set sidebar icon size to small"]
    # - [defaults write -g ApplePressAndHoldEnabled -bool false, Enable key repeat]

# install homebrew
# autoenv?
# disable notifications in the lock screen
# install MMD-QuickLook
# Homebrew packages
# antigen
# aria2
# arp-scan
# autoconf
# automake
# axel
# bash
# binutils
# boost
# boost-python
# cmake
# colordiff
# coreutils
# curl
# direnv
# docker-machine
# docker-machine-parallels
# dry
# duti
# eigen
# ffmpeg
# fish
# flac
# freetype
# fzf
# gcc
# gdbm
# gettext
# gflags
# git
# glib
# glog
# gmp
# gnutls
# gperftools
# hdf5
# htop
# icdiff
# icu4c
# ilmbase
# imagemagick
# imgcat
# isl
# jemalloc
# jpeg
# lame
# leveldb
# libebml
# libevent
# libffi
# libidn2
# libmagic
# libmatroska
# libmpc
# libogg
# libpng
# libtasn1
# libtermkey
# libtiff
# libtool
# libunistring
# libusb
# libusb-compat
# libuv
# libvorbis
# libvterm
# libyaml
# libzip
# lmdb
# lsusb
# md5sha1sum
# mkvtoolnix
# mongodb
# mpfr
# msgpack
# ncurses
# nettle
# nmap
# node
# numpy
# opencv
# openexr
# openssl
# openssl@1.1
# p11-kit
# pandoc
# pandoc-citeproc
# pcre
# pcre2
# perl
# pidof
# pixman
# pkg-config
# protobuf
# python
# python3
# python@2
# qemu
# rbenv
# readline
# ruby
# ruby-build
# scrcpy
# sdl2
# snappy
# sphinx-doc
# sqlite
# szip
# tbb
# the_silver_searcher
# tldr
# tmux
# tree
# unibilium
# watch
# wget
# x264
# xvid
# xz
# youtube-dl
# zsh
