# Options:
# clean: Remove dead symbolic links that point to the dotfiles directory. Unless
#        the force option is set to true.
# relink: remove existing target but only if it's a symbolic link
# force: remove existing target even if it's an actual file or directory

- defaults:
    link:
        relink: true

- clean: ['~']

- link:
    ~/.zshrc: zshrc
    ~/.bashrc: bashrc
    ~/.hyper.js: hyper.js
    ~/.vimrc: vim/vimrc
    ~/.config/nvim/init.vim:
        create: true
        path: vim/vimrc
    ~/.tmux.conf: tmux.conf
    ~/.gitconfig: gitconfig
    ~/.ctags: ctags
    ~/.colordiffrc: colordiffrc
    ~/.tldrrc: tldrrc
    ~/.pandoc:
        create: true
        path: pandoc
    ~/.condarc: condarc
    ~/.dotfiles: ''
    ~/.jupyter/jupyter_notebook_config.py:
        create: true
        path: jupyter_notebook_config.py

- shell:
    - [curl -L git.io/antigen > antigen.zsh, Installing Antigen]
    - ["curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim", Installing vim-plug]
    - ["curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim", Installing vim-plug for NeoVim]
