- clean: ['~']

- link:
    ~/.config/sublime-text-3/Packages/User:
        create: true
        force: true
        path: sublime-text-3/User/
    ~/.config/Code/User/settings.json:
        create: true
        force: true
        path: vscode/settings.json
    ~/.config/Code/User/keybindings.json:
        create: true
        force: true
        path: vscode/keybindings.json
    ~/.config/Code/User/spellright.dict:
        create: true
        force: true
        path: vscode/spellright.dict
    ~/config/i3/config:
        create: true
        path: i3/config
    ~/.config/i3status/config:
        create: true
        path: i3status/i3status.conf
    ~/.config/zathura/zathurarc:
        create: true
        path: zathurarc
    ~/.config/alacritty/alacritty.yml:
        create: true
        path: config/alacritty/alacritty.yml
    ~/.Xresources: Xresources
    ~/.Xresources.d: Xresources.d
