- clean: ['~']

- link:
        ~/.zshrc:
                force: true
                path: zshrc
        ~/.vim:
                force: true
                path: vim/.vim/
        ~/.vimrc:
                force: true
                path: vim/.vimrc
        ~/.config/nvim:
                force: true
                path: vim/.vim/
        ~/.config/nvim/init.vim:
                force: true
                path: vim/.vimrc
        ~/.tmux.conf:
                force: true
                path: tmux.conf
        ~/.gitconfig:
                force: true
                path: gitconfig
        ~/.gitignore_global:
                force: true
                path: gitignore_global
        ~/.ctags:
                force: true
                path: ctags
        ~/.colordiffrc:
                force: true
                path: colordiffrc
        ~/.dotfiles: ''


- shell:
        - [git submodule update --init --recursive, Installing/Updating submodules]

