- clean: ['~']

- link:
    ~/.config/sublime-text-3/Packages/User:
        create: true
        force: true
        path: sublime-text-3/User/
    ~/.config/Code/User/settings.json: vscode/settings.json
    ~/.config/Code/User/keybindings.json: vscode/keybindings.json


