- clean: ['~']

- link:
        ~/.zshrc:
                force: true
                path: zshrc
        ~/.vim:
                force: true
                path: vim/.vim/
        ~/.vimrc:
                force: true
                path: vim/.vimrc
        ~/.dotfiles: ''


- shell:
        - [git submodule update --init --recursive, Installing/Updating submodules]
        - [fc-cache -fv ~/.fonts, Regenarting font infomation]

