format = """
$username\
$hostname\
$shlvl\
$conda\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$jobs\
$status\
$character"""

add_newline = true

[character]
success_symbol = "[❯](bold purple)"

[git_branch]
format = "[$symbol$branch]($style) "
symbol = ""

[git_status]
format = '([$all_status$ahead_behind]($style) )'
style = "dimmed white"
stashed = ""
deleted = ""
modified = "*"
conflicted = "💥"

[conda]

format = '[{$symbol$environment}](dimmed white) '
symbol = " "

[jobs]
symbol = "杖"

[cmd_duration]
format = "[ $duration]($style) "
style = "dimmed white"
min_time = 60_000
